### ISSUE TITLE
Excited to see this, how can I help?

### ISSUE THREAD

**Issue by rfay** [tyler36/ddev-browsersync#1]
So excited to see this out there. Is there a way that I can help it in the maturing process? I see there are test failures.

**Comment by tyler36** [comment]
We just need to:

- add valid tests
- get confirmation of successful usage in the wild

**Comment by tyler36** [comment]
Feedback in the wild:

- https://discord.com/channels/664580571770388500/963154810499117076/964586662380335114
- https://discord.com/channels/664580571770388500/973163167020630076

**Comment by tyler36** [comment]
Thanks for #8
